/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import javax.swing.ImageIcon;

/**
 *
 * @author La Maquina
 */
public class DetallesTarea extends javax.swing.JDialog {

    /**
     * Creates new form DetallesTarea
     */
    public DetallesTarea(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle(MainMenu.tareaSeleccionada.getTitulo() + " - Detalles");
        this.setIconImage(new ImageIcon(getClass().getResource("/iconos/ico_tarea_detalles.png")).getImage());
        this.setLocationRelativeTo(parent);
        
        tarea_title.setText(MainMenu.tareaSeleccionada.getTitulo());
        tarea_descr.setText(MainMenu.tareaSeleccionada.getDescripcion());
        tarea_estado.setText(MainMenu.tareaSeleccionada.getEstado());
        tarea_fecha_entrega.setText(MainMenu.tareaSeleccionada.getFechaEntrega());
        tarea_fecha_creacion.setText(MainMenu.tareaSeleccionada.getFechaCreacion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabpanel_tarea_detalles = new javax.swing.JTabbedPane();
        section_detalles = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        lbl_descr = new javax.swing.JLabel();
        tarea_title = new javax.swing.JLabel();
        scroll_tarea_descr = new javax.swing.JScrollPane();
        tarea_descr = new javax.swing.JTextArea();
        tab_status = new javax.swing.JPanel();
        lbl_estado = new javax.swing.JLabel();
        lbl_fecha_entrega = new javax.swing.JLabel();
        tarea_estado = new javax.swing.JLabel();
        tarea_fecha_entrega = new javax.swing.JLabel();
        tarea_fecha_creacion = new javax.swing.JLabel();
        lbl_fecha_creacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalles");
        setResizable(false);

        tabpanel_tarea_detalles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbl_title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_title.setLabelFor(tarea_title);
        lbl_title.setText("Título: ");

        lbl_descr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_descr.setLabelFor(tarea_descr);
        lbl_descr.setText("Descripción: ");

        scroll_tarea_descr.setBackground(new java.awt.Color(242, 242, 242));
        scroll_tarea_descr.setBorder(null);

        tarea_descr.setEditable(false);
        tarea_descr.setColumns(20);
        tarea_descr.setLineWrap(true);
        tarea_descr.setRows(5);
        tarea_descr.setWrapStyleWord(true);
        tarea_descr.setBorder(null);
        tarea_descr.setFocusable(false);
        tarea_descr.setOpaque(false);
        scroll_tarea_descr.setViewportView(tarea_descr);

        javax.swing.GroupLayout section_detallesLayout = new javax.swing.GroupLayout(section_detalles);
        section_detalles.setLayout(section_detallesLayout);
        section_detallesLayout.setHorizontalGroup(
            section_detallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(section_detallesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(section_detallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_tarea_descr)
                    .addGroup(section_detallesLayout.createSequentialGroup()
                        .addGroup(section_detallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(section_detallesLayout.createSequentialGroup()
                                .addComponent(lbl_title)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tarea_title))
                            .addComponent(lbl_descr))
                        .addGap(0, 302, Short.MAX_VALUE)))
                .addContainerGap())
        );
        section_detallesLayout.setVerticalGroup(
            section_detallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(section_detallesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(section_detallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_title)
                    .addComponent(tarea_title))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_descr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll_tarea_descr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        tabpanel_tarea_detalles.addTab("Detalles de la Tarea", section_detalles);

        lbl_estado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_estado.setText("Estado: ");

        lbl_fecha_entrega.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_fecha_entrega.setText("Fecha de Entrega: ");

        lbl_fecha_creacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_fecha_creacion.setText("Fecha de Creación: ");

        javax.swing.GroupLayout tab_statusLayout = new javax.swing.GroupLayout(tab_status);
        tab_status.setLayout(tab_statusLayout);
        tab_statusLayout.setHorizontalGroup(
            tab_statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_statusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_statusLayout.createSequentialGroup()
                        .addComponent(lbl_estado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tarea_estado))
                    .addGroup(tab_statusLayout.createSequentialGroup()
                        .addComponent(lbl_fecha_entrega)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tarea_fecha_entrega))
                    .addGroup(tab_statusLayout.createSequentialGroup()
                        .addComponent(lbl_fecha_creacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tarea_fecha_creacion)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        tab_statusLayout.setVerticalGroup(
            tab_statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_statusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tarea_fecha_entrega)
                    .addGroup(tab_statusLayout.createSequentialGroup()
                        .addGroup(tab_statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_estado)
                            .addComponent(tarea_estado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_fecha_entrega)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab_statusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tarea_fecha_creacion)
                    .addComponent(lbl_fecha_creacion))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        tabpanel_tarea_detalles.addTab("Estado de la Entrega", tab_status);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabpanel_tarea_detalles)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabpanel_tarea_detalles)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetallesTarea dialog = new DetallesTarea(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_descr;
    private javax.swing.JLabel lbl_estado;
    private javax.swing.JLabel lbl_fecha_creacion;
    private javax.swing.JLabel lbl_fecha_entrega;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JScrollPane scroll_tarea_descr;
    private javax.swing.JPanel section_detalles;
    private javax.swing.JPanel tab_status;
    private javax.swing.JTabbedPane tabpanel_tarea_detalles;
    private javax.swing.JTextArea tarea_descr;
    private javax.swing.JLabel tarea_estado;
    private javax.swing.JLabel tarea_fecha_creacion;
    private javax.swing.JLabel tarea_fecha_entrega;
    private javax.swing.JLabel tarea_title;
    // End of variables declaration//GEN-END:variables
}
