/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author La Maquina
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("ico_mainmenu.png")).getImage());
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Establecemos el tamaño de la ventana
        setLocationRelativeTo(null); // Centra la ventana
        setVisible(true); // Hace visible el JFrame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_tareas = new javax.swing.JTable();
        barraMenu = new javax.swing.JMenuBar();
        menu_usuario = new javax.swing.JMenu();
        submenu_cerrarSesion = new javax.swing.JMenuItem();
        submenu_modificarCuenta = new javax.swing.JMenuItem();
        submenu_eliminarCuenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Task Management");
        setPreferredSize(new java.awt.Dimension(700, 500));

        Escritorio.setBackground(new java.awt.Color(30, 61, 88));

        jScrollPane1.setBackground(new java.awt.Color(242, 242, 242));

        table_tareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título", "Descripción", "Estado", "Fecha Entrega", "Fecha Creación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_tareas);

        Escritorio.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        barraMenu.setBackground(new java.awt.Color(227, 242, 253));

        menu_usuario.setForeground(new java.awt.Color(255, 255, 255));
        menu_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/ico_userMenu.png"))); // NOI18N
        menu_usuario.setToolTipText("Usuario");
        menu_usuario.setBorderPainted(false);

        submenu_cerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/ico_logout.png"))); // NOI18N
        submenu_cerrarSesion.setText("Cerrar sesión");
        submenu_cerrarSesion.setBorderPainted(false);
        submenu_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_cerrarSesionActionPerformed(evt);
            }
        });
        menu_usuario.add(submenu_cerrarSesion);

        submenu_modificarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/ico_modifyUser.png"))); // NOI18N
        submenu_modificarCuenta.setText("Modificar cuenta");
        submenu_modificarCuenta.setBorderPainted(false);
        submenu_modificarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu_modificarCuentaActionPerformed(evt);
            }
        });
        menu_usuario.add(submenu_modificarCuenta);

        submenu_eliminarCuenta.setBackground(new java.awt.Color(244, 67, 54));
        submenu_eliminarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/ico_deleteUser.png"))); // NOI18N
        submenu_eliminarCuenta.setText("Eliminar cuenta");
        submenu_eliminarCuenta.setToolTipText("Cuidado con esto manito");
        submenu_eliminarCuenta.setBorderPainted(false);
        menu_usuario.add(submenu_eliminarCuenta);

        barraMenu.add(menu_usuario);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submenu_modificarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_modificarCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submenu_modificarCuentaActionPerformed

    private void submenu_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu_cerrarSesionActionPerformed
        // TODO add your handling code here:
        //logica.Main.cerrarSesion();
        System.out.println("User Logout...");
    }//GEN-LAST:event_submenu_cerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menu_usuario;
    private javax.swing.JMenuItem submenu_cerrarSesion;
    private javax.swing.JMenuItem submenu_eliminarCuenta;
    private javax.swing.JMenuItem submenu_modificarCuenta;
    private javax.swing.JTable table_tareas;
    // End of variables declaration//GEN-END:variables
}
