/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logica.*;

/**
 *
 * @author La Maquina
 */
public class UpdateUser extends javax.swing.JDialog {
    private static String usuarioActual = null;

    /**
     * Creates new form UpdateUser
     */
    public UpdateUser(Frame parent) {
        super(parent, true); // true establece que el diálogo es modal
        usuarioActual = MainMenu.usuarioActual;
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("ico_updateUserForm.png")).getImage());
        setLocationRelativeTo(null);
        
        // Rellenar campos con datos del usuario
        txt_name_update.setText(logica.Main.getUserByUsername(usuarioActual).getNombre());
        txt_lastname_update.setText(logica.Main.getUserByUsername(usuarioActual).getApellido());
        txt_username_update.setText(logica.Main.getUserByUsername(usuarioActual).getUsername());
        txt_password_update.setText(logica.Main.getUserByUsername(usuarioActual).getContrasena());
        
        //setVisible(true);
        System.out.println("UpdateUser displayed");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_name_update = new javax.swing.JTextField();
        txt_lastname_update = new javax.swing.JTextField();
        txt_username_update = new javax.swing.JTextField();
        txt_password_update = new javax.swing.JTextField();
        btn_actualizarUsuario = new javax.swing.JButton();
        btn_exit_update = new javax.swing.JButton();
        lbl_updateTitle = new javax.swing.JLabel();
        lbl_name_update = new javax.swing.JLabel();
        lbl_username_update = new javax.swing.JLabel();
        lbl_lastname_update = new javax.swing.JLabel();
        lbl_password_update = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Cuenta");

        btn_actualizarUsuario.setText("Actualizar Datos");
        btn_actualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarUsuarioActionPerformed(evt);
            }
        });

        btn_exit_update.setText("Volver");
        btn_exit_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exit_updateActionPerformed(evt);
            }
        });

        lbl_updateTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_updateTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_updateTitle.setText("Modificar Datos");

        lbl_name_update.setLabelFor(txt_name_update);
        lbl_name_update.setText("Nombre/s");

        lbl_username_update.setLabelFor(txt_username_update);
        lbl_username_update.setText("Username");

        lbl_lastname_update.setLabelFor(txt_lastname_update);
        lbl_lastname_update.setText("Apellido/s");

        lbl_password_update.setLabelFor(txt_password_update);
        lbl_password_update.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_name_update)
                    .addComponent(txt_name_update)
                    .addComponent(lbl_username_update)
                    .addComponent(txt_username_update, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_actualizarUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_lastname_update)
                    .addComponent(lbl_password_update)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_exit_update)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_password_update, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txt_lastname_update))))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_updateTitle)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_updateTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name_update)
                    .addComponent(lbl_lastname_update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_name_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lastname_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_username_update)
                    .addComponent(lbl_password_update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_username_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_password_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_exit_update)
                    .addComponent(btn_actualizarUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_actualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarUsuarioActionPerformed
        int id = Main.getUserByUsername(usuarioActual).getId();
        String name = txt_name_update.getText();
        String lastname = txt_lastname_update.getText();
        String username = txt_username_update.getText();
        String password = txt_password_update.getText();
        
        logica.Usuario usuario = new logica.Usuario(id, name, lastname, username, password);
        
        if (name != null && lastname != null && username != null && password != null
            && !name.equals("") && !lastname.equals("") && !username.equals("") && !password.equals("")) {
            if (logica.Main.actualizarUsuario(usuario)) {
                usuarioActual = username;
                MainMenu.usuarioActual = usuarioActual;
                System.out.println("Usuario " + usuarioActual + " actualizado.");
                JOptionPane.showMessageDialog(this, "Usuario actualizado con éxito.", "Modificar cuenta", JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar datos del usuario.", "Modificar cuenta", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Todos los campos deben estar completos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_actualizarUsuarioActionPerformed

    private void btn_exit_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exit_updateActionPerformed
        this.dispose();
        System.out.println("Exit Modificar cuenta");
    }//GEN-LAST:event_btn_exit_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateUser dialog = new UpdateUser(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizarUsuario;
    private javax.swing.JButton btn_exit_update;
    private javax.swing.JLabel lbl_lastname_update;
    private javax.swing.JLabel lbl_name_update;
    private javax.swing.JLabel lbl_password_update;
    private javax.swing.JLabel lbl_updateTitle;
    private javax.swing.JLabel lbl_username_update;
    private javax.swing.JTextField txt_lastname_update;
    private javax.swing.JTextField txt_name_update;
    private javax.swing.JTextField txt_password_update;
    private javax.swing.JTextField txt_username_update;
    // End of variables declaration//GEN-END:variables
}
