package gui;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import logica.Util;

public class Conexion extends javax.swing.JFrame {
    private static Connection connection;
    
    public Conexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_conexion = new javax.swing.JPanel();
        btn_conectar = new javax.swing.JButton();
        btn_desconectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conexión a BD remota");
        setResizable(false);

        panel_conexion.setBackground(new java.awt.Color(255, 255, 255));
        panel_conexion.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 120));

        btn_conectar.setBackground(new java.awt.Color(51, 255, 0));
        btn_conectar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_conectar.setText("Conectar");
        btn_conectar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_conectar.setFocusable(false);
        btn_conectar.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conectarActionPerformed(evt);
            }
        });
        panel_conexion.add(btn_conectar);

        btn_desconectar.setBackground(new java.awt.Color(255, 0, 0));
        btn_desconectar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_desconectar.setText("Desconectar");
        btn_desconectar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_desconectar.setFocusable(false);
        btn_desconectar.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desconectarActionPerformed(evt);
            }
        });
        panel_conexion.add(btn_desconectar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_conexion, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_conexion, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conectarActionPerformed
        LoadingScreen loadingScreen = new LoadingScreen();
        loadingScreen.setVisible(true);
        
        new Thread(() -> {
            try {
                    try (Connection conn = Util.getConnection()) {
                        if (conn != null) {
                            JOptionPane.showMessageDialog(this,
                                    "Conexión exitosa",
                                    "Conexión a BD remota",
                                    JOptionPane.INFORMATION_MESSAGE);
                            connection = conn;
                        } else {
                            System.out.println("Conexión nula.");
                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(this,
                                    "Intento de conexión fallido.\n"+e,
                                    "Conexión a BD remota",
                                    JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    System.out.println(e);
                } finally {
                    // eliminar pantalla de carga
                    loadingScreen.dispose();
                }
            /*SwingUtilities.invokeLater(() -> {
                try {
                    try (Connection conn = Util.getConnection()) {
                        if (conn != null) {
                            JOptionPane.showMessageDialog(this,
                                    "Conexión exitosa",
                                    "Conexión a BD remota",
                                    JOptionPane.INFORMATION_MESSAGE);
                            connection = conn;
                        } else {
                            System.out.println("Conexión nula.");
                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(this,
                                    "Intento de conexión fallido.\n"+e,
                                    "Conexión a BD remota",
                                    JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception e) {
                    System.out.println(e);
                } finally {
                    // eliminar pantalla de carga
                    loadingScreen.dispose();
                }
            });*/
        }).start();
    }//GEN-LAST:event_btn_conectarActionPerformed

    private void btn_desconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desconectarActionPerformed
        if (connection != null) {
            try {
                connection.close();
                connection = null;
                JOptionPane.showMessageDialog(this,
                        "Intento de desconexión exitoso.",
                        "Desconexión de BD remota",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,
                        "Intento de desconexión fallido.\n"+ex,
                        "Desconexión de BD remota",
                        JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(Conexion.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "No estás conectado a la BD remota.",
                    "Desconexión de BD remota",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_desconectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_conectar;
    private javax.swing.JButton btn_desconectar;
    private javax.swing.JPanel panel_conexion;
    // End of variables declaration//GEN-END:variables
}
