/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

/**
 *
 * @author La Maquina
 */
public class EditarTarea extends javax.swing.JDialog {

    /**
     * Creates new form EditarTarea
     */
    public EditarTarea(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_editar_tarea = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        lbl_descr = new javax.swing.JLabel();
        sp_descr = new javax.swing.JScrollPane();
        txt_descr = new javax.swing.JTextArea();
        lbl_estado = new javax.swing.JLabel();
        select_estado = new javax.swing.JComboBox<>();
        lbl_fecha_entrega = new javax.swing.JLabel();
        lbl_fecha_seleccionada = new javax.swing.JLabel();
        calendar_fecha_entrega = new com.toedter.calendar.JCalendar();
        btn_editar_tarea = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_titulo.setText("Título:");

        lbl_descr.setText("Descripción:");

        txt_descr.setColumns(20);
        txt_descr.setRows(5);
        sp_descr.setViewportView(txt_descr);

        lbl_estado.setText("Estado:");

        select_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo", "Pendiente", "Finalizado" }));

        lbl_fecha_entrega.setText("Fecha de Entrega:");

        lbl_fecha_seleccionada.setText("yyyy-mm-dd");

        btn_editar_tarea.setText("Actualizar Tarea");

        javax.swing.GroupLayout p_editar_tareaLayout = new javax.swing.GroupLayout(p_editar_tarea);
        p_editar_tarea.setLayout(p_editar_tareaLayout);
        p_editar_tareaLayout.setHorizontalGroup(
            p_editar_tareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_editar_tareaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(p_editar_tareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_titulo)
                    .addComponent(lbl_descr)
                    .addGroup(p_editar_tareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txt_titulo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sp_descr, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(20, 20, 20)
                .addGroup(p_editar_tareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_editar_tareaLayout.createSequentialGroup()
                        .addComponent(lbl_fecha_entrega)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lbl_fecha_seleccionada))
                    .addGroup(p_editar_tareaLayout.createSequentialGroup()
                        .addComponent(lbl_estado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(calendar_fecha_entrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(select_estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_editar_tareaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_editar_tarea)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_editar_tareaLayout.setVerticalGroup(
            p_editar_tareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_editar_tareaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(p_editar_tareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titulo)
                    .addComponent(lbl_estado))
                .addGap(10, 10, 10)
                .addGroup(p_editar_tareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(p_editar_tareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_descr)
                    .addComponent(lbl_fecha_entrega)
                    .addComponent(lbl_fecha_seleccionada))
                .addGap(10, 10, 10)
                .addGroup(p_editar_tareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendar_fecha_entrega, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(sp_descr))
                .addGap(18, 18, 18)
                .addComponent(btn_editar_tarea)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_editar_tarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_editar_tarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarTarea dialog = new EditarTarea(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar_tarea;
    private com.toedter.calendar.JCalendar calendar_fecha_entrega;
    private javax.swing.JLabel lbl_descr;
    private javax.swing.JLabel lbl_estado;
    private javax.swing.JLabel lbl_fecha_entrega;
    private javax.swing.JLabel lbl_fecha_seleccionada;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel p_editar_tarea;
    private javax.swing.JComboBox<String> select_estado;
    private javax.swing.JScrollPane sp_descr;
    private javax.swing.JTextArea txt_descr;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
