/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author La Maquina
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        splitPane_tareas = new javax.swing.JSplitPane();
        sp_table_tareas = new javax.swing.JScrollPane();
        table_tareas = new javax.swing.JTable();
        p_detalles_tarea = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        btn_ver_mas = new javax.swing.JButton();
        sp_descr = new javax.swing.JScrollPane();
        txt_descr = new javax.swing.JTextArea();
        menubar_principal = new javax.swing.JMenuBar();
        menu_usuario = new javax.swing.JMenu();
        menu_opc_cerrar_sesion = new javax.swing.JMenuItem();
        menu_opc_modificar_cuenta = new javax.swing.JMenuItem();
        menu_opc_eliminar_cuenta = new javax.swing.JMenuItem();
        menu_tareas = new javax.swing.JMenu();
        menu_opc_crear_tarea = new javax.swing.JMenuItem();
        menu_opc_editar_tarea = new javax.swing.JMenuItem();
        menu_opc_eliminar_tarea = new javax.swing.JMenuItem();
        tarea_menu_separator = new javax.swing.JPopupMenu.Separator();
        submenu_filtrar_tareas = new javax.swing.JMenu();
        menu_opc_filtrar_nuevo = new javax.swing.JCheckBoxMenuItem();
        menu_opc_filtrar_pendiente = new javax.swing.JCheckBoxMenuItem();
        menu_opc_filtrar_finalizado = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sp_table_tareas.setMinimumSize(new java.awt.Dimension(275, 20));

        table_tareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Título", "Descripción", "Estado", "Entrega", "Creación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sp_table_tareas.setViewportView(table_tareas);
        if (table_tareas.getColumnModel().getColumnCount() > 0) {
            table_tareas.getColumnModel().getColumn(0).setResizable(false);
            table_tareas.getColumnModel().getColumn(1).setResizable(false);
            table_tareas.getColumnModel().getColumn(2).setResizable(false);
            table_tareas.getColumnModel().getColumn(3).setResizable(false);
            table_tareas.getColumnModel().getColumn(4).setResizable(false);
            table_tareas.getColumnModel().getColumn(5).setResizable(false);
        }

        splitPane_tareas.setRightComponent(sp_table_tareas);

        p_detalles_tarea.setMinimumSize(new java.awt.Dimension(275, 100));

        lbl_titulo.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lbl_titulo.setText("Título");

        btn_ver_mas.setText("Ver más");

        txt_descr.setColumns(20);
        txt_descr.setRows(5);
        txt_descr.setText("Descripción");
        sp_descr.setViewportView(txt_descr);

        javax.swing.GroupLayout p_detalles_tareaLayout = new javax.swing.GroupLayout(p_detalles_tarea);
        p_detalles_tarea.setLayout(p_detalles_tareaLayout);
        p_detalles_tareaLayout.setHorizontalGroup(
            p_detalles_tareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_detalles_tareaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(p_detalles_tareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sp_descr, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addGroup(p_detalles_tareaLayout.createSequentialGroup()
                        .addComponent(lbl_titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ver_mas)))
                .addGap(10, 10, 10))
        );
        p_detalles_tareaLayout.setVerticalGroup(
            p_detalles_tareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_detalles_tareaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(p_detalles_tareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_titulo)
                    .addComponent(btn_ver_mas))
                .addGap(15, 15, 15)
                .addComponent(sp_descr)
                .addContainerGap(422, Short.MAX_VALUE))
        );

        splitPane_tareas.setLeftComponent(p_detalles_tarea);

        escritorio.setLayer(splitPane_tareas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane_tareas, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane_tareas)
                .addContainerGap())
        );

        menu_usuario.setText("Usuario");

        menu_opc_cerrar_sesion.setText("Cerrar sesión");
        menu_usuario.add(menu_opc_cerrar_sesion);

        menu_opc_modificar_cuenta.setText("Modificar cuenta");
        menu_usuario.add(menu_opc_modificar_cuenta);

        menu_opc_eliminar_cuenta.setText("Eliminar cuenta");
        menu_usuario.add(menu_opc_eliminar_cuenta);

        menubar_principal.add(menu_usuario);

        menu_tareas.setText("Tareas");

        menu_opc_crear_tarea.setText("Nueva Tarea");
        menu_tareas.add(menu_opc_crear_tarea);

        menu_opc_editar_tarea.setText("Editar Tarea");
        menu_opc_editar_tarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_opc_editar_tareaActionPerformed(evt);
            }
        });
        menu_tareas.add(menu_opc_editar_tarea);

        menu_opc_eliminar_tarea.setText("Eliminar Tarea");
        menu_tareas.add(menu_opc_eliminar_tarea);
        menu_tareas.add(tarea_menu_separator);

        submenu_filtrar_tareas.setText("Filtrar");

        menu_opc_filtrar_nuevo.setSelected(true);
        menu_opc_filtrar_nuevo.setText("Estado: Nuevo");
        submenu_filtrar_tareas.add(menu_opc_filtrar_nuevo);

        menu_opc_filtrar_pendiente.setSelected(true);
        menu_opc_filtrar_pendiente.setText("Estado: Pendiente");
        submenu_filtrar_tareas.add(menu_opc_filtrar_pendiente);

        menu_opc_filtrar_finalizado.setSelected(true);
        menu_opc_filtrar_finalizado.setText("Estado: Finalizado");
        submenu_filtrar_tareas.add(menu_opc_filtrar_finalizado);

        menu_tareas.add(submenu_filtrar_tareas);

        menubar_principal.add(menu_tareas);

        setJMenuBar(menubar_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_opc_editar_tareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_opc_editar_tareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_opc_editar_tareaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ver_mas;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JMenuItem menu_opc_cerrar_sesion;
    private javax.swing.JMenuItem menu_opc_crear_tarea;
    private javax.swing.JMenuItem menu_opc_editar_tarea;
    private javax.swing.JMenuItem menu_opc_eliminar_cuenta;
    private javax.swing.JMenuItem menu_opc_eliminar_tarea;
    private javax.swing.JCheckBoxMenuItem menu_opc_filtrar_finalizado;
    private javax.swing.JCheckBoxMenuItem menu_opc_filtrar_nuevo;
    private javax.swing.JCheckBoxMenuItem menu_opc_filtrar_pendiente;
    private javax.swing.JMenuItem menu_opc_modificar_cuenta;
    private javax.swing.JMenu menu_tareas;
    private javax.swing.JMenu menu_usuario;
    private javax.swing.JMenuBar menubar_principal;
    private javax.swing.JPanel p_detalles_tarea;
    private javax.swing.JScrollPane sp_descr;
    private javax.swing.JScrollPane sp_table_tareas;
    private javax.swing.JSplitPane splitPane_tareas;
    private javax.swing.JMenu submenu_filtrar_tareas;
    private javax.swing.JTable table_tareas;
    private javax.swing.JPopupMenu.Separator tarea_menu_separator;
    private javax.swing.JTextArea txt_descr;
    // End of variables declaration//GEN-END:variables
}
